### ISSUE TITLE
Stupid user doesn't know anything

### ISSUE THREAD

**Issue by timtamcs** [zuckschwerdt/switchaudio-osx#4]
I just got the brew command in and switchaudio-osx installed but idk how any of the other commands work. Just putting in "-a" or "[-a]" does not work. I'm really new and really dumb.

**Comment by zuckschwerdt** [comment]
This project relocated to https://github.com/deweller/switchaudio-osx/

You need to open a Terminal, then type `SwitchAudioSource -a`
also try `SwitchAudioSource -c` and `SwitchAudioSource -n`
